Repository AY2324S1-CS2103T-W13-1/tp, pull requests merged in 2023-11, with the labels that each got.

#116 Add useful error messages for Basic Commands
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, severity.Low

#161 Various documentation updates and bugfixes
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/index.md
  docs/team/gavino3o.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, type.Documentation

#160 Fix bugs for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/alvinlim277.md
  src/main/java/seedu/address/commons/core/ShortcutSettings.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/DeleteShortcutCommand.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Bug, type.Documentation

#177 Documentation Updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/FindPredicateMapExample.puml
  docs/images/FindCommandSequenceDiagram.png
  docs/images/FindPredicateMapExample.png
Labels: type.Documentation

#175 Documentation fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddShortcutActivityDiagram.puml
  docs/diagrams/AddShortcutCommandSequenceDiagram.puml
  docs/diagrams/DeleteShortcutActivityDiagram.puml
  docs/images/AddShortcutActivityDiagram.png
  docs/images/AddShortcutCommandSequenceDiagram.png
  docs/images/DeleteShortcutActivityDiagram.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Documentation

#181 Fix inconsistency in UG
  docs/UserGuide.md
Labels: type.Bug, type.Documentation
