Repository AY2324S1-CS2103T-W13-1/tp, pull requests merged in 2023-10, with the labels that each got.

#46 Add data management User Stories to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Essential

#47 Add Ui mockup to README
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Uimockup.png
Labels: type.Documentation, priority.Essential

#50 Edit the Quick Start for the User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.Essential

#52 Add Specialist Management User Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Essential

#57 Update site-wide settings
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Documentation, priority.Essential

#60 track specialist by specialty
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Specialist.java
  src/main/java/seedu/address/model/person/Specialty.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSpecialist.java
  src/main/java/seedu/address/ui/SpecialistCard.java
  src/main/resources/view/SpecialistListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditSpecialistDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/SpecialistTest.java
  src/test/java/seedu/address/model/person/SpecialtyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSpecialistTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditSpecialistDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SpecialistBuilder.java
  src/test/java/seedu/address/testutil/SpecialistUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Essential

#62 Display patient and specialist records separately
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserBasic.java
  src/main/java/seedu/address/logic/parser/ParserComplex.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/PersonType.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Essential

#64 Add Field Medical History for Patient
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/person/PatientTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Essential

#66 Implement FindCommand to search using prefixes
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/MedHistoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/SpecialtyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Typical

#75 Improve Code Coverage of Find Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPredicateMap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.Typical

#76 Enable Medical History to be optional and Multiple value
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/predicates/MedHistoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMedicalHistory.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/MedHistoryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Essential

#82 Fixing Bug for Medical History Display
  src/main/resources/view/DarkTheme.css
Labels: type.Bug

#81 Fix Find Command Invalid Argument Parsing
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, priority.Typical, severity.Medium

#88 Improve find command flexibility
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/MedHistoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/SpecialtyContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Enhancement, priority.Typical

#89 Delete Command Mass Operation
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement, priority.Typical

#90 Recall Recent Commands Feature
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/CommandStringStash.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/CommandStringStashTest.java
Labels: type.Enhancement, priority.Typical

#93 Add shortcuts feature
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/ShortcutSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/DeleteShortcutCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutAlias.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonAdaptedSpecialist.java
  src/test/java/seedu/address/commons/core/ShortcutSettingsTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteShortcutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Enhancement, priority.Novel

#103 Update developer guide for Shortcuts feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddShortcutActivityDiagram.puml
  docs/diagrams/AddShortcutCommandSequenceDiagram.puml
  docs/diagrams/DeleteShortcutActivityDiagram.puml
  docs/diagrams/ShortcutSettingsClassDiagram.puml
  docs/images/AddShortcutActivityDiagram.png
  docs/images/AddShortcutCommandSequenceDiagram.png
  docs/images/DeleteShortcutActivityDiagram.png
  docs/images/ShortcutSettingsClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/DeleteShortcutCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutAlias.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddShortcutCommandTest.java
Labels: type.Documentation, priority.Essential

#102 Improve Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/diagrams/ViewState1.puml
  docs/diagrams/ViewState2.puml
  docs/images/UiClassDiagram.png
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSequenceDiagram.png
  docs/images/ViewState1.png
  docs/images/ViewState2.png
Labels: type.Documentation, priority.Essential

#104 Add Find Command Feature to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/FindPredicateMapExample.puml
  docs/images/FindCommandSequenceDiagram.png
  docs/images/FindPredicateMapExample.png
Labels: type.Documentation, priority.Essential

#110 Resolve duplicate person bug
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Specialist.java
  src/test/java/seedu/address/model/person/PatientTest.java
  src/test/java/seedu/address/model/person/SpecialistTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.Essential, severity.Medium

#112 Handle duplicate commands properly when recalling commands
  src/main/java/seedu/address/model/CommandStringStash.java
  src/test/java/seedu/address/model/CommandStringStashTest.java
Labels: priority.Typical, severity.Medium

#105 Modify Edit Command to align with View Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SpecialistUtil.java
Labels: type.Enhancement, priority.Typical

#113 Fix PersonTypeBar bugs
  docs/UserGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Bug, priority.Typical, severity.Medium
